version: 2
updates:
    -   package-ecosystem: "gradle"
        directory: "/"
        schedule:
            interval: "weekly"
            day: "monday"
        open-pull-requests-limit: 5
        labels:
            - "dependencies"
        commit-message:
            prefix: "chore(deps)"
        ignore:
            -   dependency-name: "gradle-wrapper"
            -   dependency-name: "*"
                update-types: [ "version-update:semver-major" ]
            -   dependency-name: "androidx.hilt:hilt-compiler"
            -   dependency-name: "androidx.hilt:hilt-work"
            -   dependency-name: "androidx.activity:activity-ktx"
            -   dependency-name: "androidx.biometric:biometric"
            -   dependency-name: "org.conscrypt:conscrypt-android"
                
    -   package-ecosystem: "github-actions"
        directory: "/"
        schedule:
            interval: "weekly"
            day: "monday"
        open-pull-requests-limit: 5
        labels:
            - "dependencies"
            - "github-actions"
        commit-message:
            prefix: "chore(deps)"
